#binop_separator = 'Front' # unstable
#brace_style = 'SameLineWhere' # unstable
#color = 'Auto' # unstable
#combine_control_expr = true # unstable, REVIEW
control_brace_style = 'ClosingNextLine' # unstable
#empty_item_single_line = true # unstable
#enum_discrim_align_threshold = 0 # unstable, REVIEW
#fn_params_layout = 'Tall'
fn_single_line = true # unstable
format_code_in_doc_comments = true # unstable
doc_comment_block_width = 60 # unstable
group_imports = 'StdExternalCrate' # unstable
#imports_granularity = 'Preserve' # unstable
#imports_indent  = 'Block' # unstable
imports_layout = 'HorizontalVertical' # unstable
#indent_style = 'Block' # unstable
match_block_trailing_comma = true
max_width = 79
#merge_derives = true
#normalize_comments = false # unstable
#normalize_doc_attributes = false # unstable, REVIEW
#overflow_delimited_expr = false # unstable, REVIEW
#remove_nested_parens = true # REVIEW
#reorder_impl_items = false # unstable
#reorder_imports = true
#reorder_modules = true
#short_array_element_width_threshold = 10
#space_after_colon = true # unstable
#space_before_colon = false # unstable
space_around_ranges = true # unstable
#struct_field_align_threshold = 0 # unstable, REVIEW
#struct_lit_single_line = true # unstable
#trailing_comma = 'Vertical' # unstable
unstable_features = true # unstable ;)
#use_field_init_shorthand = false
#use_small_heuristics = 'Default'
#use_try_shorthand = false
#version = 'One' # unstable, REVIEW
#where_single_line = false # unstable
