name: qa

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['master', 'release-*']
  workflow_dispatch: {}

jobs:

  initialize:
    uses: ./.github/workflows/core--initializer.yaml

  # Verify that we can install and use 'emcdproj' via Pipx.
  pipx-emcdproj:
    runs-on: ubuntu-latest
    steps:

      - name: Pipx Install
        run: pipx install emcd-projects

      - name: Verify
        run: emcdproj --help

  test:
    needs: [initialize]
    uses: emcd/python-project-common/.github/workflows/xrepo--tester.yaml@gha-1
    with:
      matrix-exclusions: '${{ needs.initialize.outputs.matrix-exclusions }}'
      platforms: '${{ needs.initialize.outputs.platforms }}'
      python-descriptors: '${{ needs.initialize.outputs.python-descriptors }}'
      python-versions: '${{ needs.initialize.outputs.python-versions }}'

  report:
    needs: [initialize, test]
    uses: emcd/python-project-common/.github/workflows/xrepo--reporter.yaml@gha-1
    with:
      python-version: '${{ fromJSON(needs.initialize.outputs.python-versions)[0] }}'
