name: Reusable Claude Agent

on:
  workflow_call:
    inputs:
      allowed-tools:
        description: 'Space-separated list of allowed tools for Claude.'
        required: true
        type: string
      python-version:
        required: true
        type: string
      timeout-minutes:
        description: 'Timeout for Claude execution.'
        default: 20
        required: false
        type: number
      prompt:
        description: 'Optional prompt to send to Claude.'
        required: false
        type: string
    secrets:
      anthropic-api-key:
        description: 'Anthropic API key for Claude access.'
        required: true

jobs:

  claude:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      issues: read
      pull-requests: read
    steps:

      - name: Prepare Python and Hatch
        uses: emcd/python-project-common/.github/actions/python-hatch@master
        with:
          python-version: '${{ inputs.python-version }}'

      - name: Create CLAUDE.md Symlink
        run: |
          set -eu
          if [ -f ".auxiliary/configuration/conventions.md" ]; then
            ln -sf .auxiliary/configuration/conventions.md CLAUDE.md
            echo "::notice::Created symlink: CLAUDE.md -> .auxiliary/configuration/conventions.md"
          else
            echo "::error file=.auxiliary/configuration/conventions.md::Required conventions file not found"
            exit 1
          fi
        shell: bash

      - name: Execute Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.anthropic-api-key }}
          trigger_phrase: "/claude"
          prompt: ${{ inputs.prompt }}
          claude_args: |
            --allowedTools "${{ inputs.allowed-tools }}"
            --timeout ${{ inputs.timeout-minutes }}
